### ISSUE TITLE
Support for CD version without noCD patch

### ISSUE THREAD

**Issue by vezyr** [S2-modders/Settlers-DNG-Patches#1]
Hi,
At the beginning I wanted to say that the idea to create a patch / mod to add support for extra wide displays is great and your work is awesome!

Unfortunately the mod isn't working on CD version without noCD patch (installed using installer created by KonradAr on ModDB). The game is the polish version of The Settlers 2 10-th Anniversary with The Vikings expansion released under _"Extra Klasyka"_ series. 

After enabling `debug mode` there is a message in the console window: _"Game version not supported!"_. In the memory of the game's process there is _"Version: 11758"_ string, but it's at the address `0x6D2DB8`. 

Are you planning any further work on this mod to add support to the game without noCD patch?

**Comment by zocker-160** [comment]
Thank you for reaching out and your kind words, unfortunately I do not have a way to test the CD version without the noCD patch. 

So unless someone tells me all the needed pointer addresses in memory or creates a pull request, this is not going to happen I am afraid.

**Comment by vezyr** [comment]
Thank you for your answer, it's fully understandable, so I'm closing the issue.
