### ISSUE TITLE
How to enable FogPatch

### ISSUE THREAD

**Issue by marbel82** [S2-modders/Settlers-DNG-Patches#3]
Hi,

How to enable a FogPatch or where can I find it?

**Comment by zocker-160** [comment]
The fog patch only works when using the installer linked in the readme from ModDB, because it requires additional files not present in this repository.

**Comment by marbel82** [comment]
OK, but I can't download it, because I get Error code 520.

![image](https://github.com/user-attachments/assets/fa52bc0e-5570-44d1-9d77-0b247c55dae2)

**Comment by zocker-160** [comment]
there you go:

[Widescreen_Fix_1.11.zip](https://github.com/user-attachments/files/17278060/Widescreen_Fix_1.11.zip)

**Comment by marbel82** [comment]
I can't download this file because Windows Defender says it's a virus. Maybe this is the reason why I see code 520.

**Comment by zocker-160** [comment]
well then I am sorry, I cannot help you

**Comment by marbel82** [comment]
OK, I download it on Windows with ESET NODE32, and it's working. 

Today I also try again download from https://www.moddb.com/games/the-settlers-ii-10th-anniversary/downloads/widescreen-fix/ and I can download it without any problem.
